/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sebersih;

import javafx.application.Application;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.geometry.VPos;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;

import java.io.IOException;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;


public class App extends Application {
    private Stage primaryStage;


    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage)  {
        this.primaryStage = primaryStage;
        primaryStage.setTitle("Sebersih");

        menuUtama();
        primaryStage.show();
    }

    private void menuUtama() {
        //label kasir
        Label labelkasir = new Label("KASIR");
        labelkasir.setFont(new Font("ROCKWELL",50));
        labelkasir.setStyle("-fx-font-weight: bold; ");
        labelkasir.setAlignment(Pos.TOP_CENTER);

        //logo
        Image url = new Image("https://document-export.canva.com/btPKA/DAFTbzbtPKA/15/thumbnail/0001.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQYCGKMUHWDTJW6UD%2F20230524%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230524T115206Z&X-Amz-Expires=33420&X-Amz-Signature=862dd3d9c07498ba3f3b22e7e904ff89f09eb69a724f945c95c0225bb18c9123&X-Amz-SignedHeaders=host&response-expires=Wed%2C%2024%20May%202023%2021%3A09%3A06%20GMT");
        ImageView logo = new ImageView(url);
        logo.setImage(url);;
        logo.setFitHeight(90);
        logo.setFitWidth(220);
        
        //label sebersih
        Label labelsebersih = new Label("SEBERSIH SHOES & CARE");
        labelsebersih.setFont(new Font(18));
        labelsebersih.setStyle("-fx-font-weight: bold; ");
        labelsebersih.setAlignment(Pos.TOP_CENTER);

        // image & button keranjang
        Image url1 = new Image("https://cdn.icon-icons.com/icons2/2644/PNG/512/cart_plus_fill_icon_159642.png");
        ImageView logo1 = new ImageView(url1);
        logo1.setImage(url1);
        logo1.setFitHeight(50);
        logo1.setFitWidth(50);

        Button keranjang = new Button("MASUK");
        keranjang.setGraphic(logo1);
        keranjang.setFont(new Font("Forte", 15));
        keranjang.setStyle("-fx-background-radius: 180; -fx-pref-width: 180px; -fx-pref-height: 180px; -fx-cursor: hand;");
        keranjang.setAlignment(Pos.CENTER);
        keranjang.setOnAction(e -> sceneTransaksi());

        //membuat ketentuan tampilan
        VBox layout = new VBox();
        layout.setStyle("-fx-background-color: #5F9EA0; ");
        layout.setAlignment(Pos.TOP_CENTER);
        layout.setSpacing(20);
        layout.getChildren().addAll(labelkasir,logo,logo1,labelsebersih,keranjang);

        Scene scene = new Scene(layout, 400, 660);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private void sceneTransaksi(){
        
        //bentuk yang bersampingan
        GridPane gridpaneatas = new GridPane();
        gridpaneatas.setAlignment(Pos.TOP_CENTER);
        gridpaneatas.setHgap(130); //mengatur jarak dari sel horizontal (BACK & CLEAR)
        gridpaneatas.setVgap(15); //mengatur jarak dari sel vertikal
        gridpaneatas.setPadding(new Insets(20,20,20,20)); //mengatur jarak dari scene

        //Button back & gambarnya
        Image url1 = new Image("https://cdn.pixabay.com/photo/2013/03/29/13/39/arrow-97608_640.png");
        ImageView logokembali = new ImageView(url1);
        logokembali.setImage(url1);
        logokembali.setFitHeight(35);
        logokembali.setFitWidth(35);

        Button back = new Button("Back",logokembali );
        back.setFont(new Font("Forte", 20));
        back.setStyle("-fx-background-radius: 20; -fx-cursor: hand;");
        // back.setAlignment(Pos.TOP_LEFT);
        back.setOnAction(e -> {
            menuUtama();

        });
        gridpaneatas.add(back, 0, 0);
        GridPane.setHalignment(back, HPos.CENTER);

        Image url2 = new Image("https://cdn.pixabay.com/photo/2015/08/27/10/14/symbol-909831_640.png");
        ImageView logoclear = new ImageView(url2);
        logoclear.setImage(url2);
        logoclear.setFitHeight(35);
        logoclear.setFitWidth(35);

        Button clear = new Button("Clear",logoclear);
        clear.setFont(new Font("Forte", 20));
        clear.setStyle("-fx-background-radius: 20; -fx-cursor: hand;");
        clear.setOnAction(e -> {
            struk();
        });
        gridpaneatas.add(clear, 1, 0);
        GridPane.setValignment(clear, VPos.CENTER);

        VBox layout = new VBox();
        layout.setStyle("-fx-background-color: #5F9EA0;");
        // layout.setAlignment(Pos.TOP_CENTER);
        layout.getChildren().addAll(logokembali,logoclear,gridpaneatas);


        Scene scene = new Scene(layout, 400, 600);
        primaryStage.setScene(scene);
        primaryStage.show();

    }

    private void struk() {
        // Membuat tampilan kertas pada scene
        GridPane gridPane = new GridPane();
        gridPane.setAlignment(Pos.CENTER);
        gridPane.setPadding(new Insets(20));
        gridPane.setVgap(10);
    
        // Membuat label dan mengatur propertinya
        Label label1 = new Label("No. Transaksi:");
        Label label2 = new Label("Tanggal:");
        Label label3 = new Label("Item:");
        Label label4 = new Label("Total:");
        label1.setFont(new Font("Arial", 14));
        label2.setFont(new Font("Arial", 14));
        label3.setFont(new Font("Arial", 14));
        label4.setFont(new Font("Arial", 14));
    
        // Membuat text field untuk menampilkan data pada label
        TextField textField1 = new TextField();
        TextField textField2 = new TextField();
        TextField textField3 = new TextField();
        TextField textField4 = new TextField();
        textField1.setEditable(false);
        textField2.setEditable(false);
        textField3.setEditable(false);
        textField4.setEditable(false);
    
        // Menambahkan label dan text field pada grid pane
        gridPane.add(label1, 0, 0);
        gridPane.add(textField1, 1, 0);
        gridPane.add(label2, 0, 1);
        gridPane.add(textField2, 1, 1);
        gridPane.add(label3, 0, 2);
        gridPane.add(textField3, 1, 2);
        gridPane.add(label4, 0, 3);
        gridPane.add(textField4, 1, 3);
    
        // Membuat button "Masuk"
        Button masukButton = new Button("Masuk");
        masukButton.setFont(new Font("Arial", 14));
        masukButton.setOnAction(e -> selesai());
    
        // Menambahkan button pada grid pane
        gridPane.add(masukButton, 0, 4, 2, 1);
        GridPane.setHalignment(masukButton, HPos.CENTER);
    
        // Mengatur posisi grid pane pada scene
        VBox layout = new VBox();
        layout.setAlignment(Pos.CENTER);
        layout.getChildren().add(gridPane);
    
        // Membuat scene baru dan menampilkannya pada primary stage
        Scene scene = new Scene(layout, 400, 600);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
    
    private void selesai() {
        // Membuat tampilan kertas margin
        GridPane gridPane = new GridPane();
        gridPane.setAlignment(Pos.CENTER);
        gridPane.setPadding(new Insets(20));
        gridPane.setStyle("-fx-background-color: white;");
    
        // Menambahkan konten pada kertas margin
        Label titleLabel = new Label("Kertas Margina");
        titleLabel.setFont(new Font("Arial", 24));
        Label contentLabel = new Label("Ini adalah konten yang akan dicetak pada kertas margin.");
        contentLabel.setFont(new Font("Arial", 16));
    
        // Menambahkan konten pada grid pane
        gridPane.add(titleLabel, 0, 0);
        gridPane.add(contentLabel, 0, 1);
    
        // Membuat button "Cetak"
        Button cetakButton = new Button("Cetak");
        cetakButton.setFont(new Font("Arial", 14));
        cetakButton.setOnAction(e -> saveAsPDF());
    
        // Menambahkan button pada grid pane
        gridPane.add(cetakButton, 0, 2);
        GridPane.setHalignment(cetakButton, HPos.CENTER);
    
        // Mengatur posisi grid pane pada scene
        VBox layout = new VBox();
        layout.setAlignment(Pos.CENTER);
        layout.getChildren().add(gridPane);
    
        // Membuat scene baru dan menampilkannya pada primary stage
        Scene scene = new Scene(layout, 400, 600);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
    
    private void saveAsPDF() {
        // Membuat dokumen PDF
        PDDocument document = new PDDocument();
    
        try {
            // Membuat halaman baru
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
    
            // Membuat konten stream untuk halaman
            PDPageContentStream contentStream = new PDPageContentStream(document, page);
    
            // Menambahkan konten pada halaman
            contentStream.setFont(PDType1Font.HELVETICA_BOLD, 24);
            contentStream.beginText();
            contentStream.newLineAtOffset(50, 700);
            contentStream.showText("SEBERIH SHOES & CARE");
            contentStream.showText("nanan");
            contentStream.endText();
    
            contentStream.setFont(PDType1Font.HELVETICA, 16);
            contentStream.beginText();
            contentStream.newLineAtOffset(50, 650);
            contentStream.showText("Ini adalah konten yang akan dicetak pada kertas margin.");
            contentStream.endText();
    
            // Menutup konten stream
            contentStream.close();
    
            // Menyimpan dokumen sebagai file PDF
            document.save("kertas_margin.pdf");

            
    
            // Menampilkan dialog konfirmasi
            Alert alert = new Alert(AlertType.INFORMATION);
            alert.setTitle("Informasi");
            alert.setHeaderText(null);
            alert.setContentText("Kertas margin telah disimpan sebagai file PDF.");
            alert.showAndWait();
        } catch (IOException e) {
            // Menampilkan pesan error jika terjadi kesalahan
            Alert alert = new Alert(AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText(null);
            alert.setContentText("Terjadi kesalahan saat menyimpan dokumen sebagai file PDF.");
            alert.showAndWait();
            e.printStackTrace();
        } finally {
            // Menutup dokumen
            try {
                document.close();
            } catch (IOException e) {
                Alert alert = new Alert(AlertType.ERROR);
                alert.setTitle("Error");
                alert.setHeaderText(null);
                alert.setContentText("Terjadi kesalahan saat menutup dokumen.");
                alert.showAndWait();
                e.printStackTrace();
            }
        }
    }
    
    



}